// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeveloperTesting.Database
{
    public partial class TablePeple
    {
        public int PepleId { get; set; }
        public string PepleName { get; set; }
        public DateTime? BirthDay { get; set; }
        public int? FkReration { get; set; }

        public virtual TableRerations FkRerationNavigation { get; set; }
    }
}