// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeveloperTesting.Database
{
    public partial class TableRerations
    {
        public TableRerations()
        {
            TablePeple = new HashSet<TablePeple>();
        }

        public int RerationId { get; set; }
        public string RerationShip { get; set; }
        public string Senior { get; set; }

        public virtual ICollection<TablePeple> TablePeple { get; set; }
    }
}